name: pattern_m
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.1.3
  http: ^0.13.6
  intl: ^0.17.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  logger: ^1.1.0
  path: ^1.8.2
  path_provider: ^2.0.12
  pull_to_refresh: ^2.0.0
  riverpod_annotation: ^1.1.1

dev_dependencies:
  build_runner: ^2.3.3

  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  isar_generator: ^3.0.5
  riverpod_generator: ^1.1.1

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
